name: automerge-action
on:
  pull_request:
    types: [labeled]
    branches:
      - main/* # The branch you want to automatically merge pull request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Automatically Merge PR
        uses: plm9606/automerge_actions@1.2.3
        with:
          # The label name to automatically merge. Default is "automerge".
          # label-name:
          # The number of reviewers to automatically merge. Default is 1.
          # reviewers-number:
          # The merge method ("merge", "squash", "rebase"). Default is "merge"
          # merge-method:
          # Let the bot delete the merged branch. true or false.
          #auto-delete:
          # GitHub WebHook Secret Token
          github-token: ${{ secrets.GITHUB_TOKEN }}